### ISSUE TITLE
Issue upgrading to 2.1 on CraftCMS 4.x

### ISSUE THREAD

**Issue by adrianjean** [leowebguy/devicedetect#2]
When attempting to upgrade to 2.1 on CraftCMS 4.13.7 I get the following error using composer:

```
  Problem 1
    - leowebguy/device-detect 2.1 requires mobiledetect/mobiledetectlib ^4.8 -> found mobiledetect/mobiledetectlib[4.8.01, ..., 4.8.09] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires leowebguy/device-detect 2.1 -> satisfiable by leowebguy/device-detect[2.1].
```

**Comment by leowebguy** [comment]
Pretty sure it's not related to this plugin.
It works fine on PHP 8.1.30, Craft 4.3.17
`"leowebguy/device-detect": "^2.0",`
... just tested on my end.

![Screenshot 2024-12-29 at 12 48 00 PM](https://github.com/user-attachments/assets/03ef2de7-3d78-4db4-97bf-782b43e4af00)

Check Craft vs Release ... C4 = 2.1, C5 = 3.1
https://github.com/leowebguy/devicedetect/releases

Add config restriction to your composer.json and try again

```
"config": {
    ...
    "platform": {
        "php": "8.1"
    }
},
```
